### ISSUE TITLE
Using node native Module parse failed: Unexpected character

### ISSUE THREAD

**Issue by fanchenio** [electron/rebuild#1036]
![image](https://user-images.githubusercontent.com/88647148/197458400-7ae40618-a589-4e72-8135-e10c1d1f1e6f.png)

No problem in build stage

use in main.js

var addon = require('/build/Release/hello.node');
console.log(addon.hello());

Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders       
(Source code omitted for this binary file)

**Comment by Krist14n** [comment]
how did you solve this? I'm running into the exact issue
