### ISSUE TITLE
Error related to `.forge-meta` file

### ISSUE THREAD

**Issue by stefansundin** [electron/rebuild#1065]
Hello,

I have a script that builds my app for x64 and then arm64 and then creates a universal macOS app bundle. I just added the `afterCopy` hook ([as described in the README](https://github.com/electron/rebuild/blob/main/README.md#how-can-i-integrate-this-into-electron-packager)) to trigger `rebuild` for each architecture to ensure that all the binaries are built for the correct architecture.

However, I'm now getting this error from `makeUniversalApp`:

> Error: Expected all non-binary files to have identical SHAs when creating a universal build but "Contents/Resources/app/node_modules/uiohook-napi/build/Release/.forge-meta" did not

It seems like this case should be handled automatically. Or maybe I should be able to tell rebuilder not to create this file somehow (I don't need it when I distribute the app!). For now I will attempt to just recursively delete these files before creating the universal build.

**Comment by MarshallOfSound** [comment]
This file should be excluded from your packaged app, E.g. by using an ignore regex like `/\/.forge-meta$/i,`
