### ISSUE TITLE
Rebuilding node-canvas with electron-rebuild fails 

### ISSUE THREAD

**Issue by lqomg** [electron/rebuild#1071]
Rebuilding node-canvas with electron-rebuild fails

![image](https://user-images.githubusercontent.com/29908531/220809661-9af5deb0-42b6-4d65-a930-5c1d8a2b2e69.png)

* canvas@2.10.2
* node 18.10.0 on Win10:
* Visual Studio 2017
* electron@21.x

**Comment by linqian02** [comment]
If it is in electron@18.x The following error occurs when building。

![image](https://user-images.githubusercontent.com/29908531/220811120-8879cde9-9e07-4eb2-abae-bfcaa03b950e.png)

Same issue: [2165](https://github.com/Automattic/node-canvas/issues/2165)

**Comment by GitMurf** [comment]
This can now be closed with recent merged PR for node-canvas moving to the node-addon-api 🎉 https://github.com/Automattic/node-canvas/pull/2235

**Comment by GitMurf** [comment]
cc @lqomg
