### ISSUE TITLE
no file node_modules/.bin/electron-rebuild in 3.2.11

### ISSUE THREAD

**Issue by yyjazsf** [electron/rebuild#1081]
Version 3.2.11 does not have an electron-rebuild file under node_module/.bin. After downgrading to 3.2.10, it works normally.

There are no errors during the installation process. and I see you change build in the version...  @MarshallOfSound 

node: v16.20.0
npm: 8.19.4
macos

**Comment by MarshallOfSound** [comment]
Fixed in https://github.com/electron/rebuild/commit/02d7c66477bf8382651a5bfa52b0028d4343121c and 3.2.12
