### ISSUE TITLE
node-pre-gyp support in the same way than prebuild is supported

### ISSUE THREAD

**Issue by JCMais** [electron/rebuild#367]
@MarshallOfSound @malept pinging you folks as you are the most recent contributors, sorry to bother with this, but after looking for a similar solution I found this PR which was not accepted: https://github.com/electron/electron-rebuild/pull/170.

`node-pre-gyp` does allow you to have prebuilt binaries for electron, just like `prebuilt`. For a working example, see the assets on this release: https://github.com/JCMais/node-libcurl/releases/tag/v2.1.2-1

The trick is that to make it use the correct prebuilt binary some arguments / environment variables must be passed with the `npm install` / `yarn install` command, like:
```bash
# npm
npm install node-libcurl --runtime=electron --target=v8.2.5 --disturl=https://www.electronjs.org/headers --save

# yarn
npm_config_runtime=electron npm_config_target=v8.2.5 npm_config_disturl=https://www.electronjs.org/headers yarn add node-libcurl
```

If those flags are not passed the prebuilt binary for the current Node.js version is going to be downloaded, and then later when `electron-rebuild` is called the addon is built from source, instead of trying to use the prebuilt binary for Electron.

Is the project willing to accept a PR that adds support to it? There is no need to bring the whole `node-pre-gyp` dependency itself as the linked PR did, as the process should be similar to the one used to support `prebuild`:
https://github.com/electron/electron-rebuild/blob/c42d6c7ed3ea07b6203a686ccdbfbae6bd5f8b5f/src/rebuild.ts#L295-L336

There are multiple related issues on this repo about `node-pre-gyp` support, the most recent one is this one:
https://github.com/electron/electron-rebuild/issues/309

I should be able to dedicate some time to this PR, but I need to know if there is any possibility of it being accepted.

**Comment by liSong5713** [comment]
When   publish   this release for support node-pre-gyp?

**Comment by malept** [comment]
There is no timeline. `node-pre-gyp` is complicated because there are multiple modules which implement it (the deprecated `node-pre-gyp`, the replacement `@mapbox/node-pre-gyp`, and any forks), which may or may not have different behavior.

**Comment by liSong5713** [comment]
get it. but  electron-rebuild has  node-gyp rebuild error when i use
node-canvas  .please check
https://github.com/Automattic/node-canvas/issues/913

Mark Lee ***@***.***> 于2021年9月14日周二 下午10:39写道：

**Comment by gpetrov** [comment]
the `@mapbox/node-pre-gyp` is the new official node-pre-gyp, so can we make it compatible with it? @malept
