### ISSUE TITLE
Incorrect folder name when rebuilding "sqlite3" for arm64/x64 architecture

### ISSUE THREAD

**Issue by gmantri** [electron/rebuild#554]
I am using version 2.3.4 for electron-rebuild. When I try to rebuild "sqlite3" (version 5.0.0) for "arm64" architecture using the following command:

`electron-rebuild -m app -f -a arm64 -w sqlite3`

the rebuild operation completes however the folder name seems to be incorrect. Please see the screenshot below:

<img width="409" alt="Screenshot 2020-12-21 at 9 46 06 PM" src="https://user-images.githubusercontent.com/2417437/102797948-66b2fa80-43d6-11eb-83ab-6e33c80045ba.png">

I believe `{napi_build_version}` should be a number (probably `3`). What could be the reason for that?

**UPDATE**

Same thing happens for "x64" build as well. 

<img width="411" alt="Screenshot 2020-12-22 at 1 23 10 PM" src="https://user-images.githubusercontent.com/2417437/102863670-ec778a00-4458-11eb-8c25-e69806648b4f.png">

**Comment by marcoancona** [comment]
I can confirm the issue when trying to compile [realm-js](https://www.npmjs.com/package/realm) for Node on a Mac M1 with `electron-rebuild --force --arch=arm64`

![image](https://user-images.githubusercontent.com/2278117/104368282-27328680-551c-11eb-98e4-963a42c255ab.png)

**Comment by sators** [comment]
Same happening here...

**Comment by balajiv113** [comment]
Any update on this ??
Facing same issue as well

**Comment by Sara2009** [comment]
Same issue +1.
<img width="449" alt="image" src="https://user-images.githubusercontent.com/9332442/223386002-a04299a0-f3c7-43c2-89d3-75eed4980e8b.png">

**Comment by h3poteto** [comment]
I have the same issue.

**Comment by Sara2009** [comment]
Hi! 👋 

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@electron/rebuild@3.2.10` for the project I'm working on. It works.



Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js b/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js
index 8fd6878..a8f341c 100644
--- a/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js
+++ b/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js
@@ -46,6 +46,10 @@ class NodeGyp extends _1.NativeModule {
     }
     async buildArgsFromBinaryField() {
         const binary = await this.packageJSONFieldWithDefault('binary', {});
+        let napi_build_version;
+        if (binary.napi_versions) {
+          napi_build_version = this.nodeAPI.getNapiVersion(binary.napi_versions)
+        }
         const flags = await Promise.all(Object.entries(binary).map(async ([binaryKey, binaryValue]) => {
             if (binaryKey === 'napi_versions') {
                 return;
@@ -60,6 +64,9 @@ class NodeGyp extends _1.NativeModule {
                 .replace('{arch}', this.rebuilder.arch)
                 .replace('{version}', await this.packageJSONField('version'))
                 .replace('{libc}', await detect_libc_1.default.family() || 'unknown');
+            if (napi_build_version) {
+              value = value.replace('{napi_build_version}', napi_build_version)
+            }
             for (const [replaceKey, replaceValue] of Object.entries(binary)) {
                 value = value.replace(`{${replaceKey}}`, replaceValue);
             }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Slapbox** [comment]
@Sara2009 huge huge thanks for diving into this and sharing the solution.

For anyone not familiar with `patch-package`, the name of the file you put those contents into should be (assuming using `@electron/rebuild@3.2.10`) - `@electron+rebuild+3.2.10.patch`

**Comment by MarshallOfSound** [comment]
Is there a PR for this or are people just using patch package and not sending the fix upstream?

**Comment by Slapbox** [comment]
@MarshallOfSound thanks for your speedy reply - I'll submit one once I am able to confirm this works on an ARM64 machine as well. Right now I can only confirm it fixed my issue for x64 - although I presume this is a universal-friendly solution.

**Comment by mmaietta** [comment]
@MarshallOfSound finally got the tests working across mac, linux 12/14/16, and windows. Its tests cover both `napi_build_versions` and `libc` macros.

PR is ready for review: https://github.com/electron/rebuild/pull/1078

**Comment by nikhilro** [comment]
Running into this. Just wanted to bump on getting the PR merged in. Thank you 🙏

**Comment by nikhilro** [comment]
Hey @MarshallOfSound, mind restarting the CI for the merged fix. 

Timed out before releasing: https://github.com/electron/rebuild/runs/12949338516
